VIA_ENABLE = yes
VIAL_ENABLE = yes

LTO_ENABLE = yes
RGB_MATRIX_ENABLE = no
BACKLIGHT_ENABLE = no
COMBO_ENABLE = no

CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no

SPACE_CADET_ENABLE = no